-- =================================================================
-- SCRIPT DE INSERÇÃO E ATUALIZAÇÃO (UPSERT) PARA A TABELA 'clientes'
-- =================================================================
-- Este script insere novos clientes e atualiza os existentes.
-- Ele usa a coluna 'nome' como referência única para identificar cada cliente.
-- Valores vazios da planilha são convertidos para NULL no banco de dados.

-- Ajustar constraints: remover UNIQUE de codigo e adicionar UNIQUE em nome
-- (múltiplos clientes podem ter o mesmo código, mas cada nome é único)

-- Remover constraint UNIQUE de codigo se existir
DO $$ 
BEGIN
    IF EXISTS (
        SELECT 1 FROM pg_constraint 
        WHERE conname = 'clientes_codigo_key' 
        AND conrelid = 'public.clientes'::regclass
    ) THEN
        ALTER TABLE public.clientes DROP CONSTRAINT clientes_codigo_key;
    END IF;
END $$;

-- Adicionar constraint UNIQUE em nome se não existir
DO $$ 
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint 
        WHERE conname = 'clientes_nome_key' 
        AND conrelid = 'public.clientes'::regclass
    ) THEN
        ALTER TABLE public.clientes ADD CONSTRAINT clientes_nome_key UNIQUE (nome);
    END IF;
END $$;

WITH dados_raw AS (
    SELECT 
        format('%s', codigo) AS codigo,
        format('%s', nome) AS nome,
        format('%s', endereco) AS endereco,
        format('%s', cidade) AS cidade,
        format('%s', uf) AS uf,
        format('%s', bairro) AS bairro,
        format('%s', rede) AS rede,
        format('%s', vendedor) AS vendedor,
        format('%s', loja) AS loja,
        format('%s', regiao) AS regiao,
        latitude,
        longitude
    FROM (VALUES
    (1899, 'Assai Barris', NULL, 'Salvador', 'BA', NULL, 'Assai', 'Nixon', 51, NULL, NULL, NULL),
    (1899, 'Assai Cabula', NULL, 'Salvador', 'BA', NULL, 'Assai', 'Nixon', 52, NULL, NULL, NULL),
    (1899, 'Assai Calcada', NULL, 'Salvador', 'BA', NULL, 'Assai', 'Nixon', 39, NULL, NULL, NULL),
    (1899, 'Assai Camacari', NULL, 'Camacari', 'BA', NULL, 'Assai', 'Nixon', 35, NULL, NULL, NULL),
    (1899, 'Assai Feira Sobradinho', NULL, 'Feira De Santana', 'BA', NULL, 'Assai', 'Nixon', 13, NULL, NULL, NULL),
    (1899, 'Assai Feira Tomba', NULL, 'Feira De Santana', 'BA', NULL, 'Assai', 'Nixon', 75, NULL, NULL, NULL),
    (1899, 'Assai Imbui', NULL, 'Salvador', 'BA', NULL, 'Assai', 'Nixon', 74, NULL, NULL, NULL),
    (1899, 'Assai Inacio Barbosa (Adelia)', NULL, 'Aracaju', 'SE', NULL, 'Assai', 'Nixon', 54, NULL, NULL, NULL),
    (1899, 'Assai Juazeiro', NULL, 'Juazeiro', 'BA', NULL, 'Assai', 'Antonio', 81, NULL, NULL, NULL),
    (1899, 'Assai Lauro De Freitas', NULL, 'Lauro De Freitas', 'BA', NULL, 'Assai', 'Nixon', 34, NULL, NULL, NULL),
    (1899, 'Assai Luis Anselmo (Rotula)', NULL, 'Salvador', 'BA', NULL, 'Assai', 'Nixon', 67, NULL, NULL, NULL),
    (1899, 'Assai Mussurunga', NULL, 'Salvador', 'BA', NULL, 'Assai', 'Nixon', 37, NULL, NULL, NULL),
    (1899, 'Assai N Sra Do Socorro', NULL, 'Nossa Senhora Do Socorro', 'SE', NULL, 'Assai', 'Nixon', 66, NULL, NULL, NULL),
    (1899, 'Assai Norte (Jose Conrado)', NULL, 'Aracaju', 'SE', NULL, 'Assai', 'Nixon', 42, NULL, NULL, NULL),
    (1899, 'Assai Paripe', NULL, 'Salvador', 'BA', NULL, 'Assai', 'Nixon', 36, NULL, NULL, NULL),
    (1899, 'Assai Pau Da Lima (Golf)', NULL, 'Salvador', 'BA', NULL, 'Assai', 'Nixon', 38, NULL, NULL, NULL),
    (1899, 'Assai Petrolina', NULL, 'Petrolina', 'PE', NULL, 'Assai', 'Antonio', 79, NULL, NULL, NULL),
    (1899, 'Assai Porto Itabaiana', NULL, 'Itabaiana', 'SE', NULL, 'Assai', 'Nixon', 44, NULL, NULL, NULL),
    (1899, 'Assai Sr Do Bonfim', NULL, 'Senhor Do Bonfim', 'BA', NULL, 'Assai', 'Antonio', 80, NULL, NULL, NULL),
    (1899, 'Assai Sul (Aeroporto)', NULL, 'Aracaju', 'SE', NULL, 'Assai', 'Nixon', 43, NULL, NULL, NULL),
    (1899, 'Assai Vasco Da Gama', NULL, 'Salvador', 'BA', NULL, 'Assai', 'Nixon', 53, NULL, NULL, NULL),
    (2, 'Atac Barros Reis', NULL, 'Salvador', 'BA', NULL, 'Atacadao', 'Nixon', 25, NULL, NULL, NULL),
    (48, 'Atac Cabula', NULL, 'Salvador', 'BA', NULL, 'Atacadao', 'Nixon', 20, NULL, NULL, NULL),
    (2, 'Atac Cajazeiras', NULL, 'Salvador', 'BA', NULL, 'Atacadao', 'Nixon', 27, NULL, NULL, NULL),
    (2, 'Atac Camacari', NULL, 'Camacari', 'BA', NULL, 'Atacadao', 'Nixon', 38, NULL, NULL, NULL),
    (48, 'Atac Camacari Centro', NULL, 'Camacari', 'BA', NULL, 'Atacadao', 'Nixon', 17, NULL, NULL, NULL),
    (2, 'Atac Feira Santana', NULL, 'Feira De Santana', 'BA', NULL, 'Atacadao', 'Nixon', 28, NULL, NULL, NULL),
    (2, 'Atac Lauro Freitas', NULL, 'Lauro De Freitas', 'BA', NULL, 'Atacadao', 'Nixon', 26, NULL, NULL, NULL),
    (48, 'Atac Mares', NULL, 'Salvador', 'BA', NULL, 'Atacadao', 'Nixon', 8, NULL, NULL, NULL),
    (2, 'Atacadao Brotas', NULL, 'Salvador', 'BA', NULL, 'Atacadao', 'Nixon', 72, NULL, NULL, NULL),
    (2, 'Atacadao Cam Das Arvores', NULL, 'Salvador', 'BA', NULL, 'Atacadao', 'Nixon', 73, NULL, NULL, NULL),
    (2, 'Atacadao Canabrava', NULL, 'Salvador', 'BA', NULL, 'Atacadao', 'Nixon', 76, NULL, NULL, NULL),
    (2, 'Atacadao Mata Escura', NULL, 'Salvador', 'BA', NULL, 'Atacadao', 'Nixon', 77, NULL, NULL, NULL),
    (2, 'Atacadao Parque Bela Vista', NULL, 'Salvador', 'BA', NULL, 'Atacadao', 'Nixon', 75, NULL, NULL, NULL),
    (2, 'Atacadao Petrolina', NULL, 'Petrolina', 'PE', NULL, 'Atacadao', 'Antonio', 51, NULL, NULL, NULL),
    (2, 'Atacadao Simoes Filho', NULL, 'Simoes Filho', 'BA', NULL, 'Atacadao', 'Nixon', 71, NULL, NULL, NULL),
    (2, 'Atacadao Subae Feira', NULL, 'Feira De Santana', 'BA', NULL, 'Atacadao', 'Nixon', 70, NULL, NULL, NULL),
    (48, 'Maxxi Bonoco', NULL, 'Salvador', 'BA', NULL, 'Atacadao', 'Nixon', 15, NULL, NULL, NULL),
    (48, 'Maxxi Lauro', NULL, 'Lauro De Freitas', 'BA', NULL, 'Atacadao', 'Nixon', 7, NULL, NULL, NULL),
    (48, 'Maxxi Pau Da Lima', NULL, 'Salvador', 'BA', NULL, 'Atacadao', 'Nixon', 6, NULL, NULL, NULL),
    (213, 'Atakarejo Alagoinhas', NULL, 'Alagoinhas', 'BA', NULL, 'Atakarejo', 'Ricardo Santos', 29, NULL, NULL, NULL),
    (213, 'Atakarejo Aracaju Adelia', NULL, 'Aracaju', 'SE', NULL, 'Atakarejo', 'Ricardo Santos', 21, NULL, NULL, NULL),
    (213, 'Atakarejo Aracaju Paraiso', NULL, 'Aracaju', 'SE', NULL, 'Atakarejo', 'Ricardo Santos', 46, NULL, NULL, NULL),
    (213, 'Atakarejo Baixa De Quintas', NULL, 'Salvador', 'BA', NULL, 'Atakarejo', 'Ricardo Santos', 28, NULL, NULL, NULL),
    (213, 'Atakarejo Boca Do Rio', NULL, 'Salvador', 'BA', NULL, 'Atakarejo', 'Ricardo Santos', 7, NULL, NULL, NULL),
    (213, 'Atakarejo Camacari', NULL, 'Camacari', 'BA', NULL, 'Atakarejo', 'Ricardo Santos', 13, NULL, NULL, NULL),
    (213, 'Atakarejo Catu', NULL, 'Catu', 'BA', NULL, 'Atakarejo', 'Ricardo Santos', 41, NULL, NULL, NULL),
    (213, 'Atakarejo Cd Simoes Filho', NULL, 'Simoes Filho', 'BA', NULL, 'Atakarejo', 'Ricardo Santos', 12, NULL, NULL, NULL),
    (213, 'Atakarejo Cd V. Da Conquista', NULL, 'Vitoria Da Conquista', 'BA', NULL, 'Atakarejo', 'Ricardo Santos', 18, NULL, NULL, NULL),
    (213, 'Atakarejo Dias Davila', NULL, 'Dias D''Avila', 'BA', NULL, 'Atakarejo', 'Ricardo Santos', 38, NULL, NULL, NULL),
    (213, 'Atakarejo Estancia', NULL, 'Estancia', 'SE', NULL, 'Atakarejo', 'Ricardo Santos', 47, NULL, NULL, NULL),
    (213, 'Atakarejo Feira Barauna', NULL, 'Feira De Santana', 'BA', NULL, 'Atakarejo', 'Ricardo Santos', 19, NULL, NULL, NULL),
    (213, 'Atakarejo Feira Mangabeira', NULL, 'Feira De Santana', 'BA', NULL, 'Atakarejo', 'Ricardo Santos', 39, NULL, NULL, NULL),
    (213, 'Atakarejo Feira Sim', NULL, 'Feira De Santana', 'BA', NULL, 'Atakarejo', 'Ricardo Santos', 40, NULL, NULL, NULL),
    (213, 'Atakarejo Iguatemi', NULL, 'Salvador', 'BA', NULL, 'Atakarejo', 'Ricardo Santos', 1, NULL, NULL, NULL),
    (213, 'Atakarejo Ilha Vera Cruz', NULL, 'Vera Cruz', 'BA', NULL, 'Atakarejo', 'Ricardo Santos', 17, NULL, NULL, NULL),
    (213, 'Atakarejo Ilheus', NULL, 'Ilheus', 'BA', NULL, 'Atakarejo', 'Ricardo Santos', 20, NULL, NULL, NULL),
    (213, 'Atakarejo Itabaiana', NULL, 'Itabaiana', 'SE', NULL, 'Atakarejo', 'Ricardo Santos', 45, NULL, NULL, NULL),
    (213, 'Atakarejo Itacimirim', NULL, 'Camacari', 'BA', NULL, 'Atakarejo', 'Ricardo Santos', 16, NULL, NULL, NULL),
    (213, 'Atakarejo Lagarto', NULL, 'Lagarto', 'SE', NULL, 'Atakarejo', 'Ricardo Santos', 44, NULL, NULL, NULL),
    (213, 'Atakarejo Lauro', NULL, 'Lauro De Freitas', 'BA', NULL, 'Atakarejo', 'Ricardo Santos', 2, NULL, NULL, NULL),
    (213, 'Atakarejo N. Senhora Da Gloria', NULL, 'Nossa Senhora Da Gloria', 'SE', NULL, 'Atakarejo', 'Ricardo Santos', 43, NULL, NULL, NULL),
    (213, 'Atakarejo Patamares', NULL, 'Salvador', 'BA', NULL, 'Atakarejo', 'Ricardo Santos', 14, NULL, NULL, NULL),
    (213, 'Atakarejo Pernambues', NULL, 'Salvador', 'BA', NULL, 'Atakarejo', 'Ricardo Santos', 11, NULL, NULL, NULL),
    (213, 'Atakarejo Piata', NULL, 'Salvador', 'BA', NULL, 'Atakarejo', 'Ricardo Santos', 5, NULL, NULL, NULL),
    (213, 'Atakarejo Pinto De Aguiar', NULL, 'Salvador', 'BA', NULL, 'Atakarejo', 'Ricardo Santos', 31, NULL, NULL, NULL),
    (213, 'Atakarejo Pojuca', NULL, 'Pojuca', 'BA', NULL, 'Atakarejo', 'Ricardo Santos', 33, NULL, NULL, NULL),
    (213, 'Atakarejo Porto Seguro', NULL, 'Porto Seguro', 'BA', NULL, 'Atakarejo', 'Ricardo Santos', 22, NULL, NULL, NULL),
    (213, 'Atakarejo S. Goncalo Dos Campos', NULL, 'Sao Goncalo Dos Campos', 'BA', NULL, 'Atakarejo', 'Ricardo Santos', 25, NULL, NULL, NULL),
    (213, 'Atakarejo Salvador', NULL, 'Salvador', 'BA', NULL, 'Atakarejo', 'Ricardo Santos', 9, NULL, NULL, NULL),
    (213, 'Atakarejo Sete De Abril', NULL, 'Salvador', 'BA', NULL, 'Atakarejo', 'Ricardo Santos', 32, NULL, NULL, NULL),
    (213, 'Atakarejo Simoes Filho Lj', NULL, 'Simoes Filho', 'BA', NULL, 'Atakarejo', 'Ricardo Santos', 30, NULL, NULL, NULL),
    (213, 'Atakarejo Vasco', NULL, 'Salvador', 'BA', NULL, 'Atakarejo', 'Ricardo Santos', 15, NULL, NULL, NULL),
    (213, 'Atakarejo Vitoria Da Conquista', NULL, 'Vitoria Da Conquista', 'BA', NULL, 'Atakarejo', 'Ricardo Santos', 23, NULL, NULL, NULL),
    (4383, 'Cdp Alagoinhas', NULL, 'Alagoinhas', 'BA', NULL, 'Cesta Do Povo', 'Ricardo Santos', 1, NULL, NULL, NULL),
    (4245, 'Cdp Alagoinhas Loja', NULL, 'Alagoinhas', 'BA', NULL, 'Cesta Do Povo', 'Nixon', 4, NULL, NULL, NULL),
    (4245, 'Cdp Armacao Stiep Loja', NULL, 'Salvador', 'BA', NULL, 'Cesta Do Povo', 'Nixon', 1, NULL, NULL, NULL),
    (2647, 'Cdp Boca Do Rio Loja', NULL, 'Salvador', 'BA', NULL, 'Cesta Do Povo', 'Nixon', 1, NULL, NULL, NULL),
    (4245, 'Cdp Castelo Branco Loja', NULL, 'Salvador', 'BA', NULL, 'Cesta Do Povo', 'Nixon', 7, NULL, NULL, NULL),
    (4382, 'Cdp Catu Loja', NULL, 'Catu', 'BA', NULL, 'Cesta Do Povo', 'Nixon', 1, NULL, NULL, NULL),
    (5085, 'Cdp Cd Monte Libano', NULL, 'Mata De Sao Joao', 'BA', NULL, 'Cesta Do Povo', 'Nixon', 1, NULL, NULL, NULL),
    (4245, 'Cdp Centro Dias Davila', NULL, 'Dias D''Avila', 'BA', NULL, 'Cesta Do Povo', 'Nixon', 15, NULL, NULL, NULL),
    (4245, 'Cdp CentroSede', NULL, 'Mata De Sao Joao', 'BA', NULL, 'Cesta Do Povo', 'Nixon', 16, NULL, NULL, NULL),
    (4245, 'Cdp Manoel Dia D''Avila Loja', NULL, 'Dias D''Avila', 'BA', NULL, 'Cesta Do Povo', 'Nixon', 6, NULL, NULL, NULL),
    (4245, 'Cdp Marechal Rondon Loja', NULL, 'Salvador', 'BA', NULL, 'Cesta Do Povo', 'Nixon', 9, NULL, NULL, NULL),
    (4245, 'Cdp Mata Premium Lj', NULL, 'Mata De Sao Joao', 'BA', NULL, 'Cesta Do Povo', 'Nixon', 3, NULL, NULL, NULL),
    (4245, 'Cdp Ogunja Loja', NULL, 'Salvador', 'BA', NULL, 'Cesta Do Povo', 'Nixon', 8, NULL, NULL, NULL),
    (4245, 'Cdp Rodoviaria Loja', NULL, 'Salvador', 'BA', NULL, 'Cesta Do Povo', 'Nixon', 5, NULL, NULL, NULL),
    (4245, 'Cdp Sao Caetano Loja', NULL, 'Salvador', 'BA', NULL, 'Cesta Do Povo', 'Nixon', 10, NULL, NULL, NULL),
    (2797, 'Cdp Sete Portas Loja', NULL, 'Salvador', 'BA', NULL, 'Cesta Do Povo', 'Nixon', 1, NULL, NULL, NULL),
    (4245, 'Cdp Sete Portas Novo', NULL, 'Salvador', 'BA', NULL, 'Cesta Do Povo', 'Nixon', 19, NULL, NULL, NULL),
    (4245, 'Cdp Super Centro Mata Loja', NULL, 'Mata De Sao Joao', 'BA', NULL, 'Cesta Do Povo', 'Nixon', 2, NULL, NULL, NULL),
    (4245, 'Cdp Super Mata Loja', NULL, 'Mata De Sao Joao', 'BA', NULL, 'Cesta Do Povo', 'Nixon', 11, NULL, NULL, NULL),
    (4245, 'Cesta Do Povo Boca Do Rio', NULL, 'Salvador', 'BA', NULL, 'Cesta Do Povo', 'Nixon', 17, NULL, NULL, NULL),
    (4245, 'Cesta Do Povo Catu', NULL, 'Catu', 'BA', NULL, 'Cesta Do Povo', 'Nixon', 18, NULL, NULL, NULL),
    (2819, 'Compre Bem Alagoinhas', NULL, 'Alagoinhas', 'BA', NULL, 'Compre Bem', 'Nixon', 1, NULL, NULL, NULL),
    (4379, 'Compre Bem Conselheiro Junq', NULL, 'Alagoinhas', 'BA', NULL, 'Compre Bem', 'Nixon', 3, NULL, NULL, NULL),
    (4379, 'Compre Bem Dantas Luma', NULL, 'Alagoinhas', 'BA', NULL, 'Compre Bem', 'Nixon', 4, NULL, NULL, NULL),
    (4379, 'Rede Compre Bem', NULL, 'Alagoinhas', 'BA', NULL, 'Compre Bem', 'Nixon', 1, NULL, NULL, NULL),
    (4379, 'Supermercado Compre Bem', NULL, 'Alagoinhas', 'BA', NULL, 'Compre Bem', 'Nixon', 2, NULL, NULL, NULL),
    (1600, 'Dist Sao Roque Calumbi', NULL, 'Feira De Santana', 'BA', NULL, 'Dist Sao Roque', 'Nixon', 4, NULL, NULL, NULL),
    (1600, 'Dist Sao Roque Centro', NULL, 'Feira De Santana', 'BA', NULL, 'Dist Sao Roque', 'Nixon', 2, NULL, NULL, NULL),
    (1600, 'Dist Sao Roque Conceicao', NULL, 'Feira De Santana', 'BA', NULL, 'Dist Sao Roque', 'Nixon', 7, NULL, NULL, NULL),
    (1600, 'Dist Sao Roque Mangabeira', NULL, 'Feira De Santana', 'BA', NULL, 'Dist Sao Roque', 'Nixon', 3, NULL, NULL, NULL),
    (1600, 'Dist Sao Roque Sim', NULL, 'Feira De Santana', 'BA', NULL, 'Dist Sao Roque', 'Nixon', 5, NULL, NULL, NULL),
    (1600, 'Dist Sao Roque Sta Monica', NULL, 'Feira De Santana', 'BA', NULL, 'Dist Sao Roque', 'Nixon', 1, NULL, NULL, NULL),
    (1600, 'Dist Sao Roque Sto Estevao', NULL, 'Santo Estevao', 'BA', NULL, 'Dist Sao Roque', 'Nixon', 6, NULL, NULL, NULL),
    (1600, 'Dist Sao Roque Artemia Pires', NULL, 'Feira De Santana', 'BA', NULL, 'Dist Sao Roque', 'Nixon', 8, NULL, NULL, NULL),
    (6049, 'Economart Feira De Santana', NULL, 'Feira De Santana', 'BA', NULL, 'Economart', 'Nixon', 1, NULL, NULL, NULL),
    (6049, 'Economart Itabuna', NULL, 'Itabuna', 'BA', NULL, 'Economart', 'Nixon', 7, NULL, NULL, NULL),
    (6049, 'Economart Jequie', NULL, 'Jequie', 'BA', NULL, 'Economart', 'Nixon', 3, NULL, NULL, NULL),
    (6049, 'Economart Luis Eduardo', NULL, 'Luis Eduardo Magalhaes', 'BA', NULL, 'Economart', 'Nixon', 4, NULL, NULL, NULL),
    (6049, 'Economart Santo Antonio', NULL, 'Santo Antonio De Jesus', 'BA', NULL, 'Economart', 'Nixon', 6, NULL, NULL, NULL),
    (6049, 'Economart Vitoria Da Conquista', NULL, 'Vitoria Da Conquista', 'BA', NULL, 'Economart', 'Nixon', 2, NULL, NULL, NULL),
    (1926, 'Feirao Das Frutas Atras Da Banca', NULL, 'Petrolina', 'PE', NULL, 'Feirao das Frutas', 'Antonio', 1, NULL, NULL, NULL),
    (1926, 'Feirao Das Frutas Maria Auxiliadora', NULL, 'Petrolina', 'PE', NULL, 'Feirao das Frutas', 'Antonio', 2, NULL, NULL, NULL),
    (82, 'G Barbosa Farolandia', NULL, 'Aracaju', 'SE', NULL, 'G Barbosa', 'Vinicius', 64, NULL, NULL, NULL),
    (82, 'G Barbosa Hiper Norte', NULL, 'Aracaju', 'SE', NULL, 'G Barbosa', 'Vinicius', 55, NULL, NULL, NULL),
    (82, 'G. Barbosa Francisco Porto', NULL, 'Aracaju', 'SE', NULL, 'G Barbosa', 'Vinicius', 61, NULL, NULL, NULL),
    (82, 'G. Barbosa Rio Mar', NULL, 'Aracaju', 'SE', NULL, 'G Barbosa', 'Vinicius', 53, NULL, NULL, NULL),
    (82, 'Gbarbosa Alagoinhas Loja 23', NULL, 'Alagoinhas', 'BA', NULL, 'G Barbosa', 'Vinicius', 23, NULL, NULL, NULL),
    (82, 'Gbarbosa Alagoinhas Loja 22', NULL, 'Alagoinhas', 'BA', NULL, 'G Barbosa', 'Vinicius', 22, NULL, NULL, NULL),
    (82, 'Gbarbosa Brotas', NULL, 'Salvador', 'BA', NULL, 'G Barbosa', 'Vinicius', 29, NULL, NULL, NULL),
    (82, 'Gbarbosa Cabula', NULL, 'Salvador', 'BA', NULL, 'G Barbosa', 'Vinicius', 47, NULL, NULL, NULL),
    (82, 'Gbarbosa Camacari', NULL, 'Camacari', 'BA', NULL, 'G Barbosa', 'Vinicius', 86, NULL, NULL, NULL),
    (82, 'Gbarbosa Cd Bahia', NULL, 'Simoes Filho', 'BA', NULL, 'G Barbosa', 'Vinicius', 85, NULL, NULL, NULL),
    (82, 'Gbarbosa Cd N. S. do Socorro II', NULL, 'Nossa Senhora Do Socorro', 'SE', NULL, 'G Barbosa', 'Vinicius', 87, NULL, NULL, NULL),
    (82, 'Gbarbosa Cd N. S.do Socorro I', NULL, 'Nossa Senhora Do Socorro', 'SE', NULL, 'G Barbosa', 'Vinicius', 84, NULL, NULL, NULL),
    (82, 'Gbarbosa Costa Azul', NULL, 'Salvador', 'BA', NULL, 'G Barbosa', 'Vinicius', 9, NULL, NULL, NULL),
    (82, 'Gbarbosa Feira De Santana I', NULL, 'Feira De Santana', 'BA', NULL, 'G Barbosa', 'Vinicius', 15, NULL, NULL, NULL),
    (82, 'Gbarbosa Feira De Santana II', NULL, 'Feira De Santana', 'BA', NULL, 'G Barbosa', 'Vinicius', 16, NULL, NULL, NULL),
    (82, 'Gbarbosa Feira De Santana III', NULL, 'Feira De Santana', 'BA', NULL, 'G Barbosa', 'Vinicius', 17, NULL, NULL, NULL),
    (82, 'Gbarbosa Guarajuba', NULL, 'Camacari', 'BA', NULL, 'G Barbosa', 'Vinicius', 48, NULL, NULL, NULL),
    (82, 'Gbarbosa Hiper Sul', NULL, 'Aracaju', 'SE', NULL, 'G Barbosa', 'Vinicius', 70, NULL, NULL, NULL),
    (82, 'Gbarbosa Horto Bela Vista', NULL, 'Salvador', 'BA', NULL, 'G Barbosa', 'Vinicius', 49, NULL, NULL, NULL),
    (82, 'Gbarbosa Iguatemi', NULL, 'Salvador', 'BA', NULL, 'G Barbosa', 'Vinicius', 8, NULL, NULL, NULL),
    (82, 'Gbarbosa Jardins', NULL, 'Aracaju', 'SE', NULL, 'G Barbosa', 'Vinicius', 68, NULL, NULL, NULL),
    (82, 'Gbarbosa Juazeiro Centro', NULL, 'Juazeiro', 'BA', NULL, 'G Barbosa', 'Antonio', 37, NULL, NULL, NULL),
    (82, 'Gbarbosa Juazeiro Santo Antonio', NULL, 'Juazeiro', 'BA', NULL, 'G Barbosa', 'Antonio', 33, NULL, NULL, NULL),
    (82, 'Gbarbosa Lauro De Freitas', NULL, 'Lauro De Freitas', 'BA', NULL, 'G Barbosa', 'Vinicius', 11, NULL, NULL, NULL),
    (82, 'Gbarbosa Luzia', NULL, 'Aracaju', 'SE', NULL, 'G Barbosa', 'Vinicius', 73, NULL, NULL, NULL),
    (82, 'Gbarbosa Marcos Freire N. Socorro', NULL, 'Nossa Senhora Do Socorro', 'SE', NULL, 'G Barbosa', 'Vinicius', 82, NULL, NULL, NULL),
    (82, 'Gbarbosa Sao Cristovao', NULL, 'Sao Cristovao', 'SE', NULL, 'G Barbosa', 'Vinicius', 74, NULL, NULL, NULL),
    (82, 'Gbarbosa Sobradinho Feira', NULL, 'Feira De Santana', 'BA', NULL, 'G Barbosa', 'Vinicius', 25, NULL, NULL, NULL),
    (82, 'Gbarbosa Tomba Feira', NULL, 'Feira De Santana', 'BA', NULL, 'G Barbosa', 'Vinicius', 26, NULL, NULL, NULL),
    (82, 'Gbarbosa Vitoria Da Conquista I', NULL, 'Vitoria Da Conquista', 'BA', NULL, 'G Barbosa', 'Vinicius', 39, NULL, NULL, NULL),
    (82, 'Gbarbosa Vitoria Da Conquista II', NULL, 'Vitoria Da Conquista', 'BA', NULL, 'G Barbosa', 'Vinicius', 30, NULL, NULL, NULL),
    (4582, 'Hiper Carne Jabotiana', NULL, 'Aracaju', 'SE', NULL, 'Hipercarnes', 'Vinicius', 1, NULL, NULL, NULL),
    (4130, 'Hiper Carnes Barra', NULL, 'Barra Dos Coqueiros', 'SE', NULL, 'Hipercarnes', 'Vinicius', 1, NULL, NULL, NULL),
    (2613, 'Hiper Ideal Cd', NULL, 'Salvador', 'BA', NULL, 'Hiperideal', 'Ricardo Santos', 24, NULL, NULL, NULL),
    (2613, 'Hiperideal Alphaville', NULL, 'Salvador', 'BA', NULL, 'Hiperideal', 'Ricardo Santos', 32, NULL, NULL, NULL),
    (2613, 'Hiperideal Amazonas', NULL, 'Salvador', 'BA', NULL, 'Hiperideal', 'Ricardo Santos', 27, NULL, NULL, NULL),
    (2613, 'Hiperideal Armacao', NULL, 'Salvador', 'BA', NULL, 'Hiperideal', 'Ricardo Santos', 2, NULL, NULL, NULL),
    (2613, 'Hiperideal Buraquinho', NULL, 'Lauro De Freitas', 'BA', NULL, 'Hiperideal', 'Ricardo Santos', 8, NULL, NULL, NULL),
    (2613, 'Hiperideal Caminho Das Arvores', NULL, 'Salvador', 'BA', NULL, 'Hiperideal', 'Ricardo Santos', 25, NULL, NULL, NULL),
    (2613, 'Hiperideal Feira De Santana', NULL, 'Feira De Santana', 'BA', NULL, 'Hiperideal', 'Ricardo Santos', 31, NULL, NULL, NULL),
    (2613, 'Hiperideal Jardins Acm', NULL, 'Salvador', 'BA', NULL, 'Hiperideal', 'Ricardo Santos', 30, NULL, NULL, NULL),
    (2613, 'Hiperideal Orla', NULL, 'Salvador', 'BA', NULL, 'Hiperideal', 'Ricardo Santos', 28, NULL, NULL, NULL),
    (2613, 'Hiperideal Parque Shopping', NULL, 'Lauro De Freitas', 'BA', NULL, 'Hiperideal', 'Ricardo Santos', 21, NULL, NULL, NULL),
    (2613, 'Hiperideal Piata Orlando Gomes', NULL, 'Salvador', 'BA', NULL, 'Hiperideal', 'Ricardo Santos', 19, NULL, NULL, NULL),
    (2613, 'Hiperideal Piata Otavio Mangabeira', NULL, 'Salvador', 'BA', NULL, 'Hiperideal', 'Ricardo Santos', 7, NULL, NULL, NULL),
    (2613, 'Hiperideal Praia Do Forte', NULL, 'Mata De Sao Joao', 'BA', NULL, 'Hiperideal', 'Ricardo Santos', 3, NULL, NULL, NULL),
    (2613, 'Hiperideal Vasco Da Gama', NULL, 'Salvador', 'BA', NULL, 'Hiperideal', 'Ricardo Santos', 29, NULL, NULL, NULL),
    (2613, 'Hiperideal Vitoria', NULL, 'Salvador', 'BA', NULL, 'Hiperideal', 'Ricardo Santos', 4, NULL, NULL, NULL),
    (2613, 'Serrana Canela', NULL, 'Salvador', 'BA', NULL, 'Hiperideal', 'Ricardo Santos', 26, NULL, NULL, NULL),
    (2613, 'Serrana Graca', NULL, 'Salvador', 'BA', NULL, 'Hiperideal', 'Ricardo Santos', 10, NULL, NULL, NULL),
    (2613, 'Serrana Guarajuba Monte Gordo', NULL, 'Camacari', 'BA', NULL, 'Hiperideal', 'Ricardo Santos', 22, NULL, NULL, NULL),
    (2613, 'Serrana Itaigara', NULL, 'Salvador', 'BA', NULL, 'Hiperideal', 'Ricardo Santos', 16, NULL, NULL, NULL),
    (2613, 'Serrana Jardim Apipema', NULL, 'Salvador', 'BA', NULL, 'Hiperideal', 'Ricardo Santos', 17, NULL, NULL, NULL),
    (2613, 'Serrana Patamares Loja 23', NULL, 'Salvador', 'BA', NULL, 'Hiperideal', 'Ricardo Santos', 23, NULL, NULL, NULL),
    (2613, 'Serrana Patamares Loja 13', NULL, 'Salvador', 'BA', NULL, 'Hiperideal', 'Ricardo Santos', 13, NULL, NULL, NULL),
    (2613, 'Serrana Pituba Loja 12', NULL, 'Salvador', 'BA', NULL, 'Hiperideal', 'Ricardo Santos', 12, NULL, NULL, NULL),
    (2613, 'Serrana Pituba Loja 18', NULL, 'Salvador', 'BA', NULL, 'Hiperideal', 'Ricardo Santos', 18, NULL, NULL, NULL),
    (2613, 'Serrana Praia Do Forte', NULL, 'Mata De Sao Joao', 'BA', NULL, 'Hiperideal', 'Ricardo Santos', 14, NULL, NULL, NULL),
    (2613, 'Serrana Stella Maris', NULL, 'Salvador', 'BA', NULL, 'Hiperideal', 'Ricardo Santos', 5, NULL, NULL, NULL),
    (2613, 'Serrana Stella Maris Ii', NULL, 'Salvador', 'BA', NULL, 'Hiperideal', 'Ricardo Santos', 6, NULL, NULL, NULL),
    (2613, 'Serrana Tororo', NULL, 'Salvador', 'BA', NULL, 'Hiperideal', 'Ricardo Santos', 9, NULL, NULL, NULL),
    (2613, 'Serrana Vila Laura', NULL, 'Salvador', 'BA', NULL, 'Hiperideal', 'Ricardo Santos', 15, NULL, NULL, NULL),
    (2613, 'SerranaBarra', NULL, 'Salvador', 'BA', NULL, 'Hiperideal', 'Ricardo Santos', 11, NULL, NULL, NULL),
    (2652, 'Massimo Barra', NULL, 'Barra Dos Coqueiros', 'SE', NULL, 'Massimo', 'Vinicius', 3, NULL, NULL, NULL),
    (2652, 'Massimo Farolandia', NULL, 'Aracaju', 'SE', NULL, 'Massimo', 'Vinicius', 2, NULL, NULL, NULL),
    (2652, 'Massimo Luzia', NULL, 'Aracaju', 'SE', NULL, 'Massimo', 'Vinicius', 1, NULL, NULL, NULL),
    (2459, 'Mateus Aracaju Santa Monica', NULL, 'Aracaju', 'SE', NULL, 'Mateus', 'Ricardo Santos', 'D5', NULL, NULL, NULL),
    (1456, 'Mateus Cd Feira De Santana', NULL, 'Sao Goncalo Dos Campos', 'BA', NULL, 'Mateus', 'Ricardo Santos', 12, NULL, NULL, NULL),
    (2459, 'Mateus Conceicao Do Coite', NULL, 'Conceicao Do Coite', 'BA', NULL, 'Mateus', 'Antonio', 53, NULL, NULL, NULL),
    (2459, 'Mateus Eunapolis', NULL, 'Eunapolis', 'BA', NULL, 'Mateus', 'Ricardo Santos', 97, NULL, NULL, NULL),
    (2459, 'Mateus Itabuna', NULL, 'Itabuna', 'BA', NULL, 'Mateus', 'Ricardo Santos', 98, NULL, NULL, NULL),
    (2459, 'Mateus Jacobina', NULL, 'Jacobina', 'BA', NULL, 'Mateus', 'Antonio', 34, NULL, NULL, NULL),
    (2459, 'Mateus Jose Conrado De Araujo', NULL, 'Aracaju', 'SE', NULL, 'Mateus', 'Ricardo Santos', 42, NULL, NULL, NULL),
    (2459, 'Mateus Juazeiro', NULL, 'Juazeiro', 'BA', NULL, 'Mateus', 'Antonio', 41, NULL, NULL, NULL),
    (2459, 'Mateus N. S. da Gloria', NULL, 'Nossa Senhora Da Gloria', 'SE', NULL, 'Mateus', 'Ricardo Santos', 96, NULL, NULL, NULL),
    (2459, 'Mateus Petrolina', NULL, 'Petrolina', 'PE', NULL, 'Mateus', 'Antonio', 33, NULL, NULL, NULL),
    (2459, 'Mateus Porto Seguro', NULL, 'Porto Seguro', 'BA', NULL, 'Mateus', 'Ricardo Santos', 51, NULL, NULL, NULL),
    (2459, 'Mateus Sao Cristovao SSA', NULL, 'Salvador', 'BA', NULL, 'Mateus', 'Ricardo Santos', 'E2', NULL, NULL, NULL),
    (2459, 'Mateus Teixeira De Freitas', NULL, 'Teixeira De Freitas', 'BA', NULL, 'Mateus', 'Ricardo Santos', 52, NULL, NULL, NULL),
    (2459, 'Mateus Vitoria Da Conquista', NULL, 'Vitoria Da Conquista', 'BA', NULL, 'Mateus', 'Ricardo Santos', 49, NULL, NULL, NULL),
    (2459, 'Mateus Ilheus', NULL, 'Ilheus', 'BA', NULL, 'Mateus', 'Ricardo Santos', 'D7', NULL, NULL, NULL),
    (5081, 'Mercadinho Econ. Jardim Petrolina', NULL, 'Petrolina', 'PE', NULL, 'Mercadinho Economico', 'Antonio', 1, NULL, NULL, NULL),
    (5079, 'Mercadinho Econ. Juazeiro', NULL, 'Juazeiro', 'BA', NULL, 'Mercadinho Economico', 'Antonio', 2, NULL, NULL, NULL),
    (5079, 'Mercadinho Econ. Petrolina', NULL, 'Petrolina', 'PE', NULL, 'Mercadinho Economico', 'Antonio', 1, NULL, NULL, NULL),
    (5080, 'Mercadinho Econ. Quati Petrolina', NULL, 'Petrolina', 'PE', NULL, 'Mercadinho Economico', 'Antonio', 1, NULL, NULL, NULL),
    (4469, 'Multi Frios Juazeiro', NULL, 'Juazeiro', 'BA', NULL, 'Multi Frios', 'Antonio', 1, NULL, NULL, NULL),
    (4469, 'Multi Frios Petrolina', NULL, 'Petrolina', 'PE', NULL, 'Multi Frios', 'Antonio', 2, NULL, NULL, NULL),
    (6006, 'Armazem Cecilio Mota Jacobina', NULL, 'Jacobina', 'BA', NULL, 'Outros', 'Antonio', 1, NULL, NULL, NULL),
    (4290, 'Bontempo Petrolina', NULL, 'Petrolina', 'PE', NULL, 'Outros', 'Antonio', 1, NULL, NULL, NULL),
    (6007, 'Caravelas Comercial Feira', NULL, 'Feira De Santana', 'BA', NULL, 'Outros', 'Nixon', 1, NULL, NULL, NULL),
    (4585, 'CD Brasil Capim Grosso', NULL, 'Capim Grosso', 'BA', NULL, 'Outros', 'Antonio', 1, NULL, NULL, NULL),
    (218, 'Deli E Cia Graca', NULL, 'Salvador', 'BA', NULL, 'Outros', 'Ricardo Santos', 1, NULL, NULL, NULL),
    (4640, 'Eko Express Aracaju', NULL, 'Aracaju', 'SE', NULL, 'Outros', 'Vinicius', 1, NULL, NULL, NULL),
    (6123, 'Exito Supermercado Lagarto', NULL, 'Lagarto', 'SE', NULL, 'Outros', 'Vinicius', 1, NULL, NULL, NULL),
    (4236, 'Flor Da Chapada Itaberaba', NULL, 'Itaberaba', 'BA', NULL, 'Outros', 'Ricardo Santos', 1, NULL, NULL, NULL),
    (259, 'Frutos Da Terra Petrolina', NULL, 'Petrolina', 'PE', NULL, 'Outros', 'Antonio', 1, NULL, NULL, NULL),
    (1824, 'Gral Panificacao', NULL, 'Salvador', 'BA', NULL, 'Outros', 'Ricardo Santos', 1, NULL, NULL, NULL),
    (2821, 'Gran Hortifruti', NULL, 'Salvador', 'BA', NULL, 'Outros', 'Ricardo Santos', 1, NULL, NULL, NULL),
    (4586, 'Ki Distribuidora N. S. Gloria', NULL, 'Nossa Senhora Da Gloria', 'SE', NULL, 'Outros', 'Vinicius', 1, NULL, NULL, NULL),
    (4561, 'Le Delis', NULL, 'Salvador', 'BA', NULL, 'Outros', 'Nixon', 1, NULL, NULL, NULL),
    (4607, 'Mabeni Aracaju', NULL, 'Aracaju', 'SE', NULL, 'Outros', 'Vinicius', 1, NULL, NULL, NULL),
    (2776, 'Megga Atacadista', NULL, 'Aracaju', 'SE', NULL, 'Outros', 'Vinicius', 1, NULL, NULL, NULL),
    (4007, 'Megga Distribuidora', NULL, 'Aracaju', 'SE', NULL, 'Outros', 'Vinicius', 1, NULL, NULL, NULL),
    (4575, 'Mel Distribuidora', NULL, 'Aracaju', 'SE', NULL, 'Outros', 'Vinicius', 1, NULL, NULL, NULL),
    (4680, 'Mix Distribuidora Sr Bonfim', NULL, 'Senhor Do Bonfim', 'BA', NULL, 'Outros', 'Antonio', 1, NULL, NULL, NULL),
    (2399, 'Paris Delicatessen', NULL, 'Salvador', 'BA', NULL, 'Outros', 'Ricardo Santos', 1, NULL, NULL, NULL),
    (2780, 'Sua Quitanda Hortifruti', NULL, 'Aracaju', 'SE', NULL, 'Outros', 'Vinicius', 1, NULL, NULL, NULL),
    (5095, 'Supermercado Jhones Itaberaba', NULL, 'Itaberaba', 'BA', NULL, 'Outros', 'Ricardo Santos', 1, NULL, NULL, NULL),
    (6020, 'Supermercado Jl Itaberaba', NULL, 'Itaberaba', 'BA', NULL, 'Outros', 'Ricardo Santos', 1, NULL, NULL, NULL),
    (1497, 'Perboni Juazeiro', NULL, 'Juazeiro', 'BA', NULL, 'Perboni', 'Antonio', 3, NULL, NULL, NULL),
    (69, 'Perini Graca', NULL, 'Salvador', 'BA', NULL, 'Perini', 'Vinicius', 4, NULL, NULL, NULL),
    (69, 'Perini Pituba', NULL, 'Salvador', 'BA', NULL, 'Perini', 'Vinicius', 5, NULL, NULL, NULL),
    (69, 'Perini Vasco Da Gama', NULL, 'Salvador', 'BA', NULL, 'Perini', 'Vinicius', 3, NULL, NULL, NULL),
    (2860, 'Pga Juazeiro', NULL, 'Juazeiro', 'BA', NULL, 'Pga', 'Antonio', 1, NULL, NULL, NULL),
    (2860, 'Pga Petrolina', NULL, 'Petrolina', 'PE', NULL, 'Pga', 'Antonio', 2, NULL, NULL, NULL),
    (2997, 'Nunes Peixoto Itabaiana', NULL, 'Itabaiana', 'SE', NULL, 'Rede Peixoto', 'Vinicius', 1, NULL, NULL, NULL),
    (2997, 'Nunes Peixoto Novo Horizonte Gloria', NULL, 'Nossa Senhora Da Gloria', 'SE', NULL, 'Rede Peixoto', 'Vinicius', 2, NULL, NULL, NULL),
    (208, 'Coageli Lj Lauro', NULL, 'Lauro De Freitas', 'BA', NULL, 'Redemix', 'Vinicius', 2, NULL, NULL, NULL),
    (208, 'Cogeali Lj Paripe', NULL, 'Salvador', 'BA', NULL, 'Redemix', 'Vinicius', 1, NULL, NULL, NULL),
    (209, 'Masani Pituba', NULL, 'Salvador', 'BA', NULL, 'Redemix', 'Vinicius', 1, NULL, NULL, NULL),
    (1763, 'Ponto Verde Iapi', NULL, 'Salvador', 'BA', NULL, 'Redemix', 'Vinicius', 2, NULL, NULL, NULL),
    (1763, 'Ponto Verde Sete Portas', NULL, 'Salvador', 'BA', NULL, 'Redemix', 'Vinicius', 1, NULL, NULL, NULL),
    (1763, 'Ponto Verde Vila Laura', NULL, 'Salvador', 'BA', NULL, 'Redemix', 'Vinicius', 3, NULL, NULL, NULL),
    (186, 'Redemix Chame Chame', NULL, 'Salvador', 'BA', NULL, 'Redemix', 'Vinicius', 12, NULL, NULL, NULL),
    (186, 'Redemix Rio Vermelho', NULL, 'Salvador', 'BA', NULL, 'Redemix', 'Vinicius', 13, NULL, NULL, NULL),
    (186, 'Redemix Salvador Shopping', NULL, 'Salvador', 'BA', NULL, 'Redemix', 'Vinicius', 14, NULL, NULL, NULL),
    (186, 'Rmix Alphaville', NULL, 'Salvador', 'BA', NULL, 'Redemix', 'Vinicius', 4, NULL, NULL, NULL),
    (186, 'Rmix Buraquinho', NULL, 'Lauro De Freitas', 'BA', NULL, 'Redemix', 'Vinicius', 7, NULL, NULL, NULL),
    (186, 'Rmix Horto', NULL, 'Salvador', 'BA', NULL, 'Redemix', 'Vinicius', 8, NULL, NULL, NULL),
    (186, 'Rmix Imbui', NULL, 'Salvador', 'BA', NULL, 'Redemix', 'Vinicius', 2, NULL, NULL, NULL),
    (186, 'Rmix Itapua', NULL, 'Salvador', 'BA', NULL, 'Redemix', 'Vinicius', 5, NULL, NULL, NULL),
    (186, 'Rmix Ondina', NULL, 'Salvador', 'BA', NULL, 'Redemix', 'Vinicius', 9, NULL, NULL, NULL),
    (186, 'Rmix Pituba Amazonas', NULL, 'Salvador', 'BA', NULL, 'Redemix', 'Vinicius', 6, NULL, NULL, NULL),
    (186, 'Rmix Pitubinha', NULL, 'Salvador', 'BA', NULL, 'Redemix', 'Vinicius', 1, NULL, NULL, NULL),
    (186, 'Rmix Simoes Filho', NULL, 'Simoes Filho', 'BA', NULL, 'Redemix', 'Vinicius', 3, NULL, NULL, NULL),
    (186, 'Rmix Vitoria', NULL, 'Salvador', 'BA', NULL, 'Redemix', 'Vinicius', 10, NULL, NULL, NULL),
    (186, 'RmixStella Maris', NULL, 'Salvador', 'BA', NULL, 'Redemix', 'Vinicius', 11, NULL, NULL, NULL),
    (4237, 'Rocha Carnes Aracaju', NULL, 'Aracaju', 'SE', NULL, 'Rocha Carnes', 'Vinicius', 1, NULL, NULL, NULL),
    (4237, 'Rocha Carnes Barra', NULL, 'Barra Dos Coqueiros', 'SE', NULL, 'Rocha Carnes', 'Vinicius', 2, NULL, NULL, NULL),
    (6041, 'Roselly Ferreira Sales', NULL, 'Salvador', 'BA', NULL, 'Rocha Carnes', 'Vinicius', 1, NULL, NULL, NULL),
    (47, 'Sams Aracaju', NULL, 'Aracaju', 'SE', NULL, 'Sams', 'Vinicius', 7, NULL, NULL, NULL),
    (47, 'Sams Bonoco', NULL, 'Salvador', 'BA', NULL, 'Sams', 'Vinicius', 10, NULL, NULL, NULL),
    (47, 'Sams Feira De Santana', NULL, 'Feira De Santana', 'BA', NULL, 'Sams', 'Vinicius', 12, NULL, NULL, NULL),
    (47, 'Sams Lauro De Freitas', NULL, 'Lauro De Freitas', 'BA', NULL, 'Sams', 'Vinicius', 9, NULL, NULL, NULL),
    (47, 'Sams Pituba', NULL, 'Salvador', 'BA', NULL, 'Sams', 'Vinicius', 5, NULL, NULL, NULL),
    (4234, 'Sup Bombom Aracaju', NULL, 'Aracaju', 'SE', NULL, 'Sup Bombom', 'Vinicius', 3, NULL, NULL, NULL),
    (4234, 'Sup Bombom Estancia', NULL, 'Estancia', 'SE', NULL, 'Sup Bombom', 'Vinicius', 2, NULL, NULL, NULL),
    (4234, 'Sup Bombom Lagarto', NULL, 'Lagarto', 'SE', NULL, 'Sup Bombom', 'Vinicius', 1, NULL, NULL, NULL),
    (4136, 'Total Atacado Salvador', NULL, 'Salvador', 'BA', NULL, 'Total', 'Nixon', 1, NULL, NULL, NULL),
    (5116, 'Total Atacado Lauro', NULL, 'Lauro De Freitas', 'BA', NULL, 'Total', 'Nixon', 1, NULL, NULL, NULL),
    (3081, 'Trielo Ceasa Ba', NULL, 'Salvador', 'BA', NULL, 'Trielo', 'Trielo', 3, NULL, NULL, NULL),
    (203, 'Hiper Unimar Arembepe', NULL, 'Camacari', 'BA', NULL, 'Unimar', 'Nixon', 2, NULL, NULL, NULL),
    (203, 'Hiper Unimar Barra Do Pojuca', NULL, 'Camacari', 'BA', NULL, 'Unimar', 'Nixon', 1, NULL, NULL, NULL)
    ) AS t(
        codigo, 
        nome, 
        endereco, 
        cidade, 
        uf, 
        bairro, 
        rede, 
        vendedor, 
        loja, 
        regiao, 
        latitude, 
        longitude
    )
),
dados_clientes AS (
    SELECT DISTINCT ON (nome)
        codigo, 
        nome, 
        endereco, 
        cidade, 
        uf, 
        bairro, 
        rede, 
        vendedor, 
        loja, 
        regiao, 
        latitude::NUMERIC(10,8) AS latitude, 
        longitude::NUMERIC(11,8) AS longitude
    FROM dados_raw
    ORDER BY nome
)
INSERT INTO public.clientes (
    codigo, 
    nome, 
    endereco, 
    cidade, 
    uf, 
    bairro, 
    rede, 
    vendedor, 
    loja, 
    regiao, 
    latitude, 
    longitude
)
SELECT * FROM dados_clientes
ON CONFLICT (nome) DO UPDATE SET
    codigo = EXCLUDED.codigo,
    endereco = EXCLUDED.endereco,
    cidade = EXCLUDED.cidade,
    uf = EXCLUDED.uf,
    bairro = EXCLUDED.bairro,
    rede = EXCLUDED.rede,
    vendedor = EXCLUDED.vendedor,
    loja = EXCLUDED.loja,
    regiao = EXCLUDED.regiao,
    latitude = EXCLUDED.latitude,
    longitude = EXCLUDED.longitude;